name: bud
description: Beyond Use Date Drug

publish_to: 'none'

version: 0.0.4+2

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  # english_words: ^4.0.0
  # provider: ^6.0.0
  yaml: ^3.1.2
  # odoo_rpc: ^0.5.2
  http: ^1.2.0
  package_info_plus: ^8.1.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  dependency_validator: ^4.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/biyud_trans.png
    - assets/config.yaml

