name: bud
description: Beyond Use Date Drug

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  yaml: ^3.1.2
  odoo_rpc: ^0.5.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/prescription.png
    - assets/drugs.png
    - assets/config.yaml